Rakefile:
  strict_variables: false
spec/spec_helper_acceptance.rb:
  modules:
    - name: puppetlabs-stdlib
      version: 3.2.0
    - name: puppetlabs-java
      version: 1.2.0
    - name: puppetlabs-wget
      version: 1.0.0
    - name: stahnma-epel
      version: 0.1.0
      osfamily: RedHat
